/**
 * Thirty-one doors Peretz actually built, as the site draws them.
 *
 * ⚠ GENERATED BY `npm run corpus`. Do not edit by hand — every field is
 * derived from that door's own hand-measured record, and the whole point
 * of the derivation is that nobody types it. See the header of
 * `tools/corpus.mjs` for what is derived from what.
 *
 * No prices here on purpose: the page has one statement of what a door
 * costs, and it is `priceAgorot` on the state being shown.
 */
export const WORKS = [
  { id: 'd003', state: { colour: 'rb-7110d', detail: 'plain', window: 'none', grille: 'none', handle: 'none', lockset: 'plate', size: 'standard', handing: 'left-in' } },
  { id: 'd004', state: { colour: 'rb-7080d', detail: 'plain', window: 'none', grille: 'none', handle: 'none', lockset: 'plate', size: 'standard', handing: 'right-in' } },
  { id: 'd012', state: { colour: 'rb-7080d', detail: 'plain', window: 'none', grille: 'none', handle: 'none', lockset: 'plate', size: 'standard', handing: 'left-in' } },
  { id: 'd015', state: { colour: 'rb-9005d', detail: 'plain', window: 'none', grille: 'none', handle: 'none', lockset: 'coral', size: 'standard', handing: 'right-in' } },
  { id: 'd016', state: { colour: 'rb-0096d', detail: 'plain', window: 'none', grille: 'none', handle: 'none', lockset: 'coral', size: 'standard', handing: 'right-in' } },
  { id: 'd022', state: { colour: 'rb-rb09d', detail: 'plain', window: 'none', grille: 'none', handle: 'none', lockset: 'plate', size: 'standard', handing: 'right-in' } },
  { id: 'd026', state: { colour: 'rb-7080d', detail: 'plain', window: 'none', grille: 'none', handle: 'none', lockset: 'coral', size: 'standard', handing: 'right-in' } },
  { id: 'd029', state: { colour: 'rb-rb09d', detail: 'plain', window: 'none', grille: 'none', handle: 'none', lockset: 'plate', size: 'standard', handing: 'left-in' } },
  { id: 'd030', state: { colour: 'rb-0096d', detail: 'plain', window: 'none', grille: 'none', handle: 'none', lockset: 'cadoor', size: 'standard', handing: 'left-in' } },
  { id: 'd031', state: { colour: 'rb-7110d', detail: 'plain', window: 'none', grille: 'none', handle: 'none', lockset: 'cadoor', size: 'standard', handing: 'right-in' } },
  { id: 'd034', state: { colour: 'rb-0096d', detail: 'groove', window: 'none', grille: 'none', handle: 'nitzan', lockset: 'cylinder', size: 'standard', handing: 'right-in' } },
  { id: 'd038', state: { colour: 'rb-7110d', detail: 'stripsv', window: 'none', grille: 'none', handle: 'none', lockset: 'coral', size: 'standard', handing: 'right-in' } },
  { id: 'd043', state: { colour: 'rb-7126d', detail: 'stripsv', window: 'none', grille: 'none', handle: 'ron', lockset: 'cylinder', size: 'standard', handing: 'right-in' } },
  { id: 'd048', state: { colour: 'rb-5103d', detail: 'panel', window: 'none', grille: 'none', handle: 'none', lockset: 'coral', size: 'standard', handing: 'right-in' } },
  { id: 'd051', state: { colour: 'rb-7240d', detail: 'panel', window: 'none', grille: 'none', handle: 'none', lockset: 'coral', size: 'standard', handing: 'left-in' } },
  { id: 'd063', state: { colour: 'rb-7240d', detail: 'strips3', window: 'none', grille: 'none', handle: 'ron', lockset: 'cylinder', size: 'standard', handing: 'right-in' } },
  { id: 'd064', state: { colour: 'rb-7110d', detail: 'strips', window: 'none', grille: 'none', handle: 'none', lockset: 'coral', size: 'standard', handing: 'left-in' } },
  { id: 'd072', state: { colour: 'rb-0096d', detail: 'groove', window: 'none', grille: 'none', handle: 'shahar', lockset: 'cylinder', size: 'standard', handing: 'left-in' } },
  { id: 'd078', state: { colour: 'rb-7110d', detail: 'strips', window: 'none', grille: 'none', handle: 'ron', lockset: 'cylinder', size: 'standard', handing: 'right-in' } },
  { id: 'd087', state: { colour: 'rb-7021d', detail: 'panel', window: 'none', grille: 'none', handle: 'shahar', lockset: 'digital', size: 'standard', handing: 'right-in' } },
  { id: 'd092', state: { colour: 'rb-6219d', detail: 'panel', window: 'broad', grille: 'iron', handle: 'none', lockset: 'knobplate', size: 'standard', handing: 'left-in' } },
  { id: 'd097', state: { colour: 'rb-7080d', detail: 'panel', window: 'tallwin', grille: 'scroll', handle: 'none', lockset: 'coral', size: 'standard', handing: 'left-in' } },
  { id: 'd099', state: { colour: 'rb-7126d', detail: 'panel', window: 'rect', grille: 'scroll', handle: 'none', lockset: 'coral', size: 'standard', handing: 'right-in' } },
  { id: 'd106', state: { colour: 'rb-7080d', detail: 'panel', window: 'broad', grille: 'circles', handle: 'none', lockset: 'plate', size: 'standard', handing: 'left-in' } },
  { id: 'd108', state: { colour: 'rb-7080d', detail: 'panel', window: 'rect', grille: 'iron', handle: 'none', lockset: 'plate', size: 'standard', handing: 'right-in' } },
  { id: 'd113', state: { colour: 'rb-7080d', detail: 'plain', window: 'strip', grille: 'grid', handle: 'ella', lockset: 'digital', size: 'standard', handing: 'right-in' } },
  { id: 'd116', state: { colour: 'rb-7080d', detail: 'panel', window: 'rect', grille: 'scroll', handle: 'none', lockset: 'coral', size: 'standard', handing: 'right-in' } },
  { id: 'd122', state: { colour: 'rb-7240d', detail: 'panel', window: 'rect', grille: 'grid', handle: 'idan', lockset: 'cylinder', size: 'standard', handing: 'right-in' } },
  { id: 'd125', state: { colour: 'rb-9001d', detail: 'plain', window: 'strip', grille: 'reeded', handle: 'ron', lockset: 'cylinder', size: 'standard', handing: 'left-in' } },
  { id: 'd128', state: { colour: 'rb-7322d', detail: 'plain', window: 'tallwin', grille: 'iron', handle: 'idan', lockset: 'cylinder', size: 'standard', handing: 'left-in' } },
];
