#!/usr/bin/env python3
"""Trace the grape-and-vine design into js/vine.js.

The owner's son sent the design itself, 26.9.2026: research/vine/design.webp,
884 x 2000, black line work on white inside a 4 px frame, with the words
"this is how the grape and vine design really looks ... the design is really
white and not black like its here." So the drawing does not re-invent it; it
draws THIS, traced.

Committed rather than kept as a scratch harness for the reason
tools/rectify.mjs is: js/vine.js is a pure function of that picture plus the
numbers below, and re-deriving a trace from prose is how a design comes back
slightly different from the one that was approved.

    pip install pillow numpy potracer
    python3 tools/trace-vine.py

What it measures and writes, besides the outline:
  * the FRAME is dropped (4 px each side, found as rows/columns that are
    almost entirely ink), so the design runs off the pane's edges the way a
    film cut to an opening does;
  * the vertical PERIOD — the picture is 1.65 repeats of one film, and the
    best overlap of the mask with itself shifted is at 1207 px down and 6 px
    across (IoU 0.73). Hand-drawn, so not exact, which is why a copy does not
    start at the period but at the SEAM:
  * the SEAM row — where a copy shifted by one period agrees best with the
    original across a narrow band, so the join on a pane taller than the
    picture falls where the two drawings are most alike.
"""
import json, sys
from pathlib import Path
import numpy as np
from PIL import Image
import potrace

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / 'research/vine/design.webp'
OUT = ROOT / 'js/vine.js'

g = np.array(Image.open(SRC).convert('L'))
ink = g < 128
H0, W0 = ink.shape

# ── the frame ─────────────────────────────────────────────────────────────
def edge(sums, full):
    lo = 0
    while sums[lo] > full * 0.75: lo += 1
    hi = len(sums)
    while sums[hi - 1] > full * 0.75: hi -= 1
    return lo, hi
x0, x1 = edge(ink.sum(0), H0)
y0, y1 = edge(ink.sum(1), W0)
m = ink[y0:y1, x0:x1]
H, W = m.shape

# ── the period ────────────────────────────────────────────────────────────
f = m.astype(np.float32)
def iou(a, b):
    return float((a * b).sum() / max(1, ((a + b) > 0).sum()))
def shifted(p, dx):
    a, c = f[:H - p], f[p:]
    if dx > 0: a, c = a[:, dx:], c[:, :-dx]
    elif dx < 0: a, c = a[:, :dx], c[:, -dx:]
    return a, c
best = max(((iou(*shifted(p, dx)), p, dx)
            for p in range(int(H * 0.45), int(H * 0.75))
            for dx in range(-20, 21, 2)))
score, P, DX = best

# ── the seam ──────────────────────────────────────────────────────────────
BAND = 24
seam = max(((iou(f[s - BAND:s + BAND], np.roll(f[s - P - BAND:s - P + BAND], DX, axis=1)), s)
            for s in range(P + BAND, H - BAND)))[1]

# ── the outline ───────────────────────────────────────────────────────────
# ⚠ potracer fills the FALSE pixels (PIL's '1' convention, 0 = black), so it
# is handed the complement. Handed the ink itself it traces the PAPER, and the
# pane comes out white with the design showing through as clear lines.
bm = potrace.Bitmap(~m)
plist = bm.trace(turdsize=8, alphamax=1.0, opticurve=True, opttolerance=0.4)
r = lambda v: str(int(round(v)))
parts = []
for curve in plist:
    s = curve.start_point
    d = f'M{r(s.x)} {r(s.y)}'
    for seg in curve.segments:
        if seg.is_corner:
            d += f'L{r(seg.c.x)} {r(seg.c.y)}L{r(seg.end_point.x)} {r(seg.end_point.y)}'
        else:
            d += (f'C{r(seg.c1.x)} {r(seg.c1.y)} {r(seg.c2.x)} {r(seg.c2.y)} '
                  f'{r(seg.end_point.x)} {r(seg.end_point.y)}')
    parts.append(d + 'Z')
D = ''.join(parts)

OUT.write_text(f"""/**
 * The grape-and-vine design (גפן), TRACED — generated by tools/trace-vine.py
 * from research/vine/design.webp. Do not edit by hand; re-run the tool.
 *
 * Coordinates are the picture's own pixels inside its frame, {W} x {H}. The
 * drawing scales this to the pane's WIDTH (glazingArt) and repeats it down a
 * taller pane: a copy is laid {P} px further down and {DX} px across (the
 * measured period, IoU {score:.2f}), and starts at row {seam - P} of itself so
 * the join falls at row {seam} of the one above, where the two agree best.
 */
export const VINE = {json.dumps({'w': W, 'h': H, 'period': P, 'dx': DX, 'seam': seam})};
export const VINE_D = '{D}';
""")
print(f'frame {x0},{y0}-{x1},{y1} -> {W}x{H}; period {P} dx {DX} iou {score:.3f}; '
      f'seam {seam}; {len(plist)} curves, {len(D)} bytes', file=sys.stderr)
